### PR TITLE
Update view-acquisitions-report.md .Added a Note .

### PR DESCRIPTION
**Pull request by v-sumukh**
Updated the document as per the request from shganesh@microsoft.com . Added a Note to the document which indicates the latency of the report is 5 days .

### CODE REVIEW

**Comment by v-sumukh** [comment]
#Signoff

**Comment by v-sumukh** [comment]
@Labrenne @Lauragra kindly review and merge .
#sign-off

**Comment by Lauragra** [comment]
@v-sumukh , does my update to the note text look okay? The original was unclear. If so, we're good to merge.

**Comment by v-sumukh** [comment]
@Lauragra yes the edit made by you make more sense . Kindly proceed .Thank You !
#sign-off

**Pull request merged**
